export const FETCH_MOVIES_POPULAR = "FETCH_MOVIES_POPULAR";
export const FETCH_MOVIES_TOP_RATED = "FETCH_MOVIES_TOP_RATED";
export const FETCH_MOVIES_NOW_PLAYING = "FETCH_MOVIES_NOW_PLAYING";
export const FETCH_MOVIES_UPCOMING = "FETCH_MOVIES_UPCOMING";

export const SET_SELECTED_MOVIE_LIST = "SET_SELECTED_MOVIE_LIST";
export const SET_SELECTED_TV_LIST = "SET_SELECTED_TV_LIST";

export const SELECT_MOVIE = "SELECT_MOVIE";
export const SELECT_TV = "SELECT_TV";

export const FETCH_TV_POPULAR = "FETCH_TV_POPULAR";
export const FETCH_TV_TOP_RATED = "FETCH_TV_TOP_RATED";

export const ADD_TO_WATCHLIST_MOVIE = "ADD_TO_WATCHLIST_MOVIE";
export const ADD_TO_WATCHLIST_TV = "ADD_TO_WATCHLIST_TV";
export const SELECT_WATCHLIST_MOVIE = "SELECT_WATCHLIST_MOVIE";
export const SELECT_WATCHLIST_TV = "SELECT_WATCHLIST_TV";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const FETCH_SEARCH_RESULTS = "FETCH_SEARCH_RESULTS";
