export const FETCH_MOVIES_POPULAR = "FETCH_MOVIES_POPULAR";
export const FETCH_MOVIES_TOP_RATED = "FETCH_MOVIES_TOP_RATED";
export const FETCH_MOVIES_NOW_PLAYING = "FETCH_MOVIES_NOW_PLAYING";
export const FETCH_MOVIES_UPCOMING = "FETCH_MOVIES_UPCOMING";

export const SET_SELECTED_MOVIE_LIST = "SET_SELECTED_MOVIE_LIST";
export const SET_SELECTED_TV_LIST = "SET_SELECTED_TV_LIST";

export const FETCH_TV_POPULAR = "FETCH_TV_POPULAR";
export const FETCH_TV_TOP_RATED = "FETCH_TV_TOP_RATED";
